- platform: mqtt
  name: "Bedroom Table 2"
  state_topic: "/espurna/switch/sonoff_2/relay/0"
  command_topic: "/espurna/switch/sonoff_2/relay/0/set"
  payload_on: 1
  payload_off: 0
  optimistic: false
  qos: 0
  retain: true
