homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 226
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  customize: !include customize.yaml

# Enables the frontend
frontend:
  javascript_version: latest

# Enables configuration UI
config:

http:
  base_url: !secret http_url
  api_password: !secret http_password
  ssl_certificate: /config/fullchain.pem
  ssl_key: /config/privkey.pem
  cors_allowed_origins:
    - http://home.sheumaker.com:7080
  trusted_networks:
    - 192.168.1.0/24
    - 75.98.126.193

# Checks for available updates
updater:

influxdb:
  host: 192.168.1.15
  port: 8086
  database: home_assistant

# Discover some devices automatically
discovery:
  ignore:
    - wink

recorder:
  db_url: !secret mariadb_url
  purge_keep_days: 30
  exclude:
     domains:
       - automation

# Enables support for tracking state changes over time
history:
  exclude:
    entities:
      - sensor.current_time
      - sensor.current_date
      - sensor.bed_left_value
      - sensor.bed_right_value
    domains:
      - zwave
      - sun

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.current_time
      - sensor.current_date
      - sensor.bed_left_value
      - sensor.bed_right_value
    domains:
      - zwave
      - sun

# Track the sun
sun:

zone: !include_dir_merge_list zones/

remote: !include_dir_merge_list remotes/

tts:
  - platform: google

  - platform: amazon_polly
    aws_access_key_id: !secret amazon_key_id
    aws_secret_access_key: !secret amazon_secret
    region_name: 'us-east-2'
    output_format: mp3
    sample_rate: 16000

  - platform: voicerss
    api_key: !secret voice_rss_api
    language: en-us
    codec: mp3
    format: 44khz_16bit_stereo

alexa:

cloud:
  alexa:
     filter:
        exclude_domains:
          - group
          - automation
          - sensor
          - media_player


juicenet:
  access_token: !secret juicenet_key

ecobee:
  api_key: !secret ecobee_key

ring:
  username: !secret ring_user
  password: !secret ring_password

#blink:
#  username: !secret blink_user
#  password: !secret blink_password

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_key

lutron_caseta_pro:
  bridges:
     - host: !secret lutron_pro_ip
       mac: !secret lutron_pro_mac 
       cover: [ 19, 20, 21 ]
       switch: [ 17, 18 ]

alarm_control_panel:
  platform: manual
  name: “Alarm”
  code: 1234
  
octoprint:
  host: !secret octoprint_ip
  api_key: !secret octoprint_api
  bed: true
  number_of_tools: 1

emulated_hue:
  exposed_domains:
    - light
    - switch
    - fan

mqtt:
  broker: !secret mqtt_ip
  discovery: true
  discovery_prefix: homeassistant

bmw_connected_drive:
 bmw_i3:
   username: !secret bmw_user
   password: !secret bmw_password
   region: "north_america"

# usps:
#  username: !secret usps_user
#  password: !secret usps_password
#
# camera:
#  - platform: usps
#    scan_interval: 5
 
ios:

switch: !include_dir_merge_list switches/
light: !include_dir_merge_list lights/

panel_custom: !include_dir_merge_list panels/

sensor: !include_dir_merge_list sensors/
binary_sensor: !include_dir_merge_list binary_sensors/

input_boolean: !include_dir_merge_named inputs/boolean/
input_number: !include_dir_merge_named inputs/slider/
input_text: !include_dir_merge_named inputs/text/

media_player: !include_dir_merge_list media_players/
group: !include_dir_merge_named groups/
automation: !include_dir_merge_list automations/
scene: !include_dir_merge_list scenes/
script: !include_dir_merge_named scripts/
intent_script: !include_dir_merge_named intents/
camera: !include_dir_merge_list cameras/

device_tracker: !include_dir_merge_list trackers/

notify:
  - name: amazon_notifyme
    platform: rest
    message_param_name: notification
    resource: https://api.notifymyecho.com/v1/NotifyMe
    data:
      accessCode: !secret notifyme_code

aerogarden:
  username: !secret aerogarden_user
  password: !secret aerogarden_password

