- platform: mqtt
  name: 'Floor Lamp'
  state_topic: '/espurna/bulb/livingroom-led/relay/0'
  command_topic: '/espurna/bulb/livingroom-led/relay/0/set'
  payload_on: 1
  payload_off: 0
  rgb_state_topic: '/espurna/bulb/livingroom-led/color'
  rgb_command_topic: '/espurna/bulb/livingroom-led/color/set'
  rgb_value_template: '{{ "%s,%s,%s" | format(value[1:3] | int(value[1:3],16), value[3:5] | int(value[3:5], 16),  value[5:7] | int(value[5:7],16)) }}'
  rgb: true
  optimistic: false
  color_temp: true
  color_temp_command_topic: '/espurna/bulb/livingroom-led/mired/set'
  brightness: true
  brightness_scale: 255
  brightness_command_topic:  '/espurna/bulb/livingroom-led/brightness/set'
  brightness_state_topic: '/espurna/bulb/livingroom-led/brightness'
  white_value: true
  white_value_command_topic: '/espurna/bulb/livingroom-led/channel/3/set'
  white_value_state_topic: '/espurna/bulb/livingroom-led/channel/3'
