- platform: mqtt
  name: 'Kitchen Lamp'
  state_topic: /espurna/bulb/kitchen-led/relay/0
  command_topic: /espurna/bulb/kitchen-led/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: /espurna/bulb/kitchen-led/status
  payload_available: 1
  payload_not_available: 0
  brightness_state_topic: /espurna/bulb/kitchen-led/brightness
  brightness_command_topic: /espurna/bulb/kitchen-led/brightness/set
  rgb_state_topic: /espurna/bulb/kitchen-led/rgb
  rgb_command_topic: /espurna/bulb/kitchen-led/rgb/set
  color_temp_command_topic: /espurna/bulb/kitchen-led/mired/set
  white_value_state_topic: /espurna/bulb/kitchen-led/channel/3
  white_value_command_topic: /espurna/bulb/kitchen-led/channel/3/set
