- platform: darksky
  api_key: !secret darksky_key
  monitored_conditions:
    - summary
    - precip_type
    - nearest_storm_distance
    - icon
    - temperature_min
    - temperature_max
    - cloud_cover
    - temperature
    - apparent_temperature
    - hourly_summary


