# ---------------------------------
#  Basement Door / Garage Light
# ---------------------------------
- alias: Garage Light On with basement door sensor
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.basement_door_state
    to: 'open'
  action:
    service: switch.turn_on
    entity_id: 
      - switch.garage_florecent
      - switch.garage_stair_lights

- alias: Garage Light Off with basement door sensor
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.basement_door_state
    to: 'closed'
    for:
      minutes: 10
  action:
    service: switch.turn_off
    entity_id: 
      - switch.garage_florecent
      - switch.garage_stair_lights

- alias: Basement door left open
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.basement_door_state
    to: 'open'
    for:
      seconds: 30
  condition:
    condition: state
    entity_id: input_boolean.basement_door_alarm
    state: 'on'
  action:
    - service: !secret alert_kyle
      data:
        message: Basement Door Left Open
    - service: tts.voicerss_say
      entity_id: media_player.kitchen_audio_mpd
      data:
        message: Basement door left open, cats will escape
