# ---------------------------------
#  Bathroom lights
# ---------------------------------
- alias: Turn toliet on with bathroom
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: light.master_bathroom_light
    to: 'on'
  action:
    service: light.turn_on
    data_template:
        entity_id: light.master_bathroom_toliet
        brightness: "{{ state_attr('light.master_bathroom_light', 'brightness') | int }}"

- alias: Turn toliet off with bathroom
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: light.master_bathroom_light
    to: 'off'
  action:
    service: light.turn_off
    entity_id: light.master_bathroom_toliet

- alias: Turn on bathroom with motion 
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_motion_sensor
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.motion_bathroom_enable
    state: 'on'
  action:
    service: light.turn_on
    data_template:
        entity_id: light.master_bathroom_light
        brightness: '{{ states.input_number.motion_bathroom_level.state | int }}'

- alias: Turn off bathroom with no motion (15min)
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_motion_sensor
    to: 'off'
    for:
      minutes: 15
  action:
    service: light.turn_off
    entity_id: light.master_bathroom_light


