# ---------------------------------
# Bedtime
# ---------------------------------
- alias: Get in bed
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.bed_state
      to: 'Occupied'
  action:
    - service: input_boolean.turn_off
      entity_id: 
        - input_boolean.motion_bathroom_enable
        - input_boolean.motion_closet_enable
        - input_boolean.motion_stair_enable
    - service: light.turn_off
      entity_id:
        - light.master_bathroom_light
        - light.master_closet_light
        - light.stairs_lights

- alias: Get out of bed
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.bed_state
      to: 'Unoccupied'
  action:
    - service: input_boolean.turn_on
      entity_id: 
        - input_boolean.motion_bathroom_enable
        - input_boolean.motion_closet_enable
        - input_boolean.motion_stair_enable

