# ---------------------------------
# Bedtime
# ---------------------------------
- alias: Leave action
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.leave
      to: 'on'
  action:
    - service: script.turn_on
      entity_id: script.leave

- alias: Leave reset
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.leave
      from: 'off'
      to: 'on'
      for: 
        minutes: 5
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.leave
