# ---------------------------------
# Pico Remotes
# ---------------------------------
- alias: Test Pico - On
  trigger:
    - platform: state
      entity_id: sensor.test_pico
      to: '1'
  action:
    - service: light.turn_on
      entity_id: 
        - light.cabinets_left
        - light.cabinets_right

- alias: Test Pico - Off
  trigger:
    - platform: state
      entity_id: sensor.test_pico
      to: '4'
  action:
    - service: light.turn_off
      entity_id: 
        - light.cabinets_left
        - light.cabinets_right

- alias: Test Pico - Up
  trigger:
    - platform: state
      entity_id: sensor.test_pico
      to: '8'
  action:
    - service: light.toggle
      entity_id: light.cabinets_left

- alias: Test Pico - Down
  trigger:
    - platform: state
      entity_id: sensor.test_pico
      to: '16'
  action:
    - service: light.toggle
      entity_id: light.cabinets_right


- alias: Test Pico - Middle
  trigger:
    - platform: state
      entity_id: sensor.test_pico
      to: '2'
  action:
    - service: light.toggle
      entity_id: light.dining_room

# ---------------------------------
# Laundry light control
# ---------------------------------

- alias: Laundry Pico - On
  trigger:
    - platform: state
      entity_id: sensor.laundry_pico
      to: '1'
  action:
    - service: light.turn_on
      entity_id: light.laundry

- alias: Laundry Pico - Off
  trigger:
    - platform: state
      entity_id: sensor.laundry_pico
      to: '4'
  action:
    - service: light.turn_off
      entity_id: light.laundry

# ---------------------------------
# Shop Vac Pico control
# ---------------------------------

#- alias: Shop Vac 1 - On
#  trigger:
#    - platform: state
#      entity_id: sensor.shop_vac1_pico
#      to: '1'
#  action: 
#    - service: switch.turn_on
#      entity_id: switch.shop_vac_switch

#- alias: Shop Vac 1 - Off
#  trigger:
#    - platform: state
#      entity_id: sensor.shop_vac1_pico
#      to: '4'
#  action: 
#    - service: switch.turn_off
#      entity_id: switch.shop_vac_switch

