# ---------------------------------
#  Porch on at sunset
# ---------------------------------
- alias: Turn on porch when sun sets
  initial_state: True
  hide_entity: False
  trigger:
    platform: sun
    event: sunset
  action:
    service: light.turn_on
    data:
      entity_id: light.exterior_porch
      brightness: 100

- alias: Turn off porch when sun rises
  initial_state: True
  hide_entity: False
  trigger:
    platform: sun
    event: sunrise
  action:
    service: light.turn_off
    entity_id: light.exterior_porch

