# ---------------------------------
# send me a notification
# ---------------------------------
- alias: Notification Text - Home Assistant Start
  initial_state: 'on'
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: !secret alert_kyle
      data:
        message: Home Assistant Started
    - service: tts.voicerss_say
      entity_id: media_player.kitchen_audio_mpd
      data:
        message: Home Assistant Started
