# ---------------------------------
#  Shades to wake me up
# ---------------------------------
- alias: Open shades 7:15A M-F
  trigger:
    platform: time
    at: '07:15:00'
  condition:
    condition: time
    weekday:
       - mon
       - tue
       - wed
       - thu
       - fri
  action:
    service: light.turn_on
    data:
      brightness: 127
      entity_id: 
        - light.shade_left
        - light.shade_right
        - light.shade_closet
